name: issue-callenge
on: 
    # push:
    #     paths-ignore: .github\workflow\*
    workflow_dispatch: 
jobs:
    output:
        runs-on: ubuntu-latest
        steps:
            - name: output
              run: echo "output - ${{toJson(github.event)}}"
