name: action-challenge
on: push
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        outputs: 
          js-build-filename: ${{ steps.js-file.outputs.js-file-name }}
        steps:
            - name: code setup
              uses: actions/checkout@v3
            - name: install node
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: install dependency
              run: npm ci
            - name: run build
              run: npm run build
            - name: upload artifact
              uses: actions/upload-artifact@v4
              with:
                path: dist
            - name: check
              run: find dist/assets/*.js -type f
            - name: save js file name
              id: js-file
              run: find dist/assets/*.js -type f -execdir 'echo js-file-name={} >> $GITHUB_OUTPUT' ';'
    deploy:
        name: deploy
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: get build artifacts
              uses: actions/download-artifact@v4
              with: 
                path: dist
            - name: check downloads
              run: ls -R
            - name: js build file name
              run: echo "${{ needs.build.outputs.js-build-filename }}"
            - name: Step completion
              run: echo "Deploy successful"

              
              
