name: action-challenge
on: push
jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - name: code setup
              uses: actions/checkout@v3
            - name: install node
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: install dependency
              run: npm ci
            - name: run test
              run: npm test
            - name: Step completion
              run: echo "Test successful"
    build:
        name: Build
        runs-on: ubuntu-latest
        needs: [test]
        outputs: 
          js-build-filename: ${{ steps.js-file.outputs.js-file-name }}
        steps:
            - name: code setup
              uses: actions/checkout@v3
            - name: install node
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: install dependency
              run: npm ci
            - name: run build
              run: npm run build
            - name: upload artifact
              uses: actions/upload-artifact@v4
              with:
                path: dist
            - name: save js file name
              id: js-file
              run: find /dist/assests/*.js -exec js-file-name={} >> $GITHUB_OUTPUT
    deploy:
        name: deploy
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: get build artifacts
              uses: actions/download-artifact@v4
              with: 
                path: dist
            - name: check downloads
              run: ll
            - name: js build file name
              run: echo ${{ needs.build }}
            - name: Step completion
              run: echo "Deploy successful"

              
              
