name: issue-callenge
on: 
    push:
        paths-ignore: .workflow
jobs:
    output:
        runs-on: ubuntu-latest
        steps:
            - name: output
              run: echo "output - ${{toJson(github.event)}}"
