name: action-challenge
on: push
jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - name: code setup
              uses: actions/checkout@v3
            - name: install node
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: install dependency
              run: npm ci
            - name: run lint
              run: npm run lint
            - name: Step completion
              run: echo "Lint successful"
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - name: code setup
              uses: actions/checkout@v3
            - name: install node
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: install dependency
              run: npm ci
            - name: run test
              run: npm test
            - name: Step completion
              run: echo "Test successful"
    deploy:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: code setup
              uses: actions/checkout@v3
            - name: install node
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: install dependency
              run: npm ci
            - name: run build
              run: npm build
            - name: Step completion
              run: echo "Deploy successful"
                
              
